### ISSUE TITLE
Adaptation to windows 10

### ISSUE THREAD

**Issue by RyzenK8** [wakedxy/weban#2]
I suggest adapting on Windows 10. The reasons: People are not really installing Linux on their pc, beginners will be better off with a double click BAT script ?

The code of it is intended for Linux.

**Comment by AnonymousCode91** [comment]
Oui c'est ça, il faudrait que le script sois compatible avec Windows, mais on pourrait tout simplement le laisser se basé sur Python. Cela ne dérange pas l'exécution du programme…

**Comment by wakedxy** [comment]
@RyzenK8  Python is not just a language for Linux lovers, you can use is on Windows too. After if you are really interested by offensive security my advice is to use a linux distribution instead of Windows.
