### ISSUE TITLE
amerlioration securité

### ISSUE THREAD

**Issue by jeromefavrou** [wakedxy/weban#3]
dans ton projet , l'utilisation de input est une fail sous python2 et inferieur, dans une utilistion personnel ça ne pose pas probleme mais pour un code public ça peut poser probleme dans le sens ou beaucoup font des sudo python ... au lieu de python3 ...

il peut etre interessant de verouiller a python3 ( comme fait dans le dirsearch.py d'ailleur)

`if sys.version_info.major < 3 :`
`       print("python version may be > major 3" )`
`        exit(0)`

dans la meme optique il vaut mieux appeller "gnome-terminal" via son chemin absolut et non via le path systeme soit "/usr/bin/gnome-terminal"

apres je pense que mettre des avertissements  te dechargent de toute responsabilité juridique en commentaire  peut aussi etre utile

**Comment by wakedxy** [comment]
Bonjour Jerome , 

Merci pour ta participation, tu m'as été d'une grande aide, les modifications ont été apporté. Nous continuerons à améliorer le script :)


Cordialement,
